# Generated by Django 5.2.17 on 2026-09-21 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resettoken',
            table='reset_tokens',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
