# Generated by Django 5.2.17 on 2026-09-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_rename_tables_plural"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resettoken",
            name="token",
            field=models.TextField(),
        ),
    ]
