# Generated by Django 5.2.17 on 2026-09-29
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [('branch', '0001_initial'), ('industry', '0001_initial'), ('planogram', '0001_initial'), ('zone', '0001_initial')]
    operations = [
        migrations.CreateModel(name='Demand', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('title', models.CharField(max_length=255)), ('description', models.CharField(blank=True, max_length=255, null=True)),
            ('start_date', models.DateTimeField()), ('end_date', models.DateTimeField(blank=True, null=True)),
            ('repetition_type', models.CharField(blank=True, max_length=16, null=True)), ('status', models.CharField(default='ACTIVE', max_length=8)),
            ('target_user_roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, size=None)),
            ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)),
            ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demands', to='zone.department')),
            ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demands', to='industry.industry')),
        ], options={'db_table': 'demand'}),
        migrations.CreateModel(name='DemandBranch', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('last_execution_occurrences_sync_at', models.DateTimeField(blank=True, null=True)),
            ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demands', to='branch.branch')),
            ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='demand.demand')),
            ('planogram', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demand_branches', to='planogram.planogram')),
        ], options={'db_table': 'demand_branch', 'constraints': [models.UniqueConstraint(fields=('demand', 'branch', 'planogram'), name='demand_branch_unique')]}),
    ]
