"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2 LTS.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Defaults só servem para desenvolvimento: em produção (DEBUG=False) o boot
# falha se algum deles estiver em uso — ver checagem no fim deste arquivo.
INSECURE_SECRET_KEY = "django-insecure-change-me"
INSECURE_JWT_SECRET = "insecure-secret-change-me"

# `or`: variável definida mas vazia (ex: DJANGO_SECRET_KEY= no .env) cai no default
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY") or INSECURE_SECRET_KEY

# Seguro por padrão: debug só liga explicitamente (o docker-compose liga em dev)
DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',

    # App técnico: management commands (make_usecase), sem models
    'src._app',

    # Entidades por domínio (cada uma com seu próprio models.py)
    'src.entities.branch',
    'src.entities.product',
    'src.entities.user',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.environ.get('DB_NAME', 'django_ddd'),
        'USER': os.environ.get('DB_USER', 'django_ddd'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'django_ddd'),
        'HOST': os.environ.get('DB_HOST', 'db'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Usado só pelo django.contrib.auth (superuser/admin). O User do domínio
# (src.entities.user) usa BcryptHashService — hashes $2b$ compatíveis com o TS.
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
]

# JWT — idênticos ao config/default.yaml do backend TS

JWT_SECRET = os.environ.get("JWT_SECRET") or INSECURE_JWT_SECRET
JWT_AUDIENCE = os.environ.get("JWT_AUDIENCE", "gestao-por-espaco")
JWT_ISSUER = os.environ.get("JWT_ISSUER", "https://ge.drogariaglobo.com.br")
JWT_ACCESS_TOKEN_EXPIRES_IN = os.environ.get("JWT_ACCESS_TOKEN_EXPIRES_IN", "1h")
JWT_ID_TOKEN_EXPIRES_IN = os.environ.get("JWT_ID_TOKEN_EXPIRES_IN", "15m")
JWT_REFRESH_TOKEN_EXPIRES_IN = os.environ.get("JWT_REFRESH_TOKEN_EXPIRES_IN", "7d")

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-BR'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'


# Segredos padrão: em produção bloqueiam o boot (vale para qualquer servidor,
# inclusive gunicorn, que não roda system checks). Em dev, o aviso vem pelo
# system check tooling.W001 (src/_app/checks.py).
_insecure_secrets = [
    name
    for name, value, default in [
        ("DJANGO_SECRET_KEY", SECRET_KEY, INSECURE_SECRET_KEY),
        ("JWT_SECRET", JWT_SECRET, INSECURE_JWT_SECRET),
    ]
    if value == default
]
if not DEBUG and _insecure_secrets:
    from django.core.exceptions import ImproperlyConfigured

    raise ImproperlyConfigured(
        f"Segredos padrão em uso com DEBUG=False: {', '.join(_insecure_secrets)}. "
        "Defina-os nas variáveis de ambiente."
    )
